import { resolvePersona } from "@/lib/personas";

/**
 * Fleet owner surface — Baba Tino.
 * Per-vehicle revenue ledger, Ghost Trip audit narrative (bilingual via Gemma),
 * ZIMRA liability card. Phase 3 work.
 */
export default async function FleetHome({
  searchParams,
}: {
  searchParams: Promise<{ as?: string }>;
}) {
  const params = await searchParams;
  const persona = await resolvePersona(params.as, "fleet_owner");

  return (
    <main className="min-h-dvh">
      <header className="border-b border-svika-teal-100 bg-svika-teal px-6 py-4 text-svika-stone">
        <h1 className="text-2xl font-semibold">Fleet · {persona.name}</h1>
        <p className="text-xs opacity-80">Phase 3 build target.</p>
      </header>

      <section className="grid grid-cols-1 gap-4 p-6 lg:grid-cols-3">
        <div className="rounded-lg border border-svika-teal-100 bg-white p-4">
          <h2 className="text-sm font-medium text-svika-mute">Today&apos;s revenue</h2>
          <p className="mt-2 text-3xl font-semibold text-svika-teal">$—</p>
        </div>
        <div className="rounded-lg border border-svika-teal-100 bg-white p-4">
          <h2 className="text-sm font-medium text-svika-mute">Stops vs fares logged</h2>
          <p className="mt-2 text-3xl font-semibold text-svika-teal">—</p>
        </div>
        <div className="rounded-lg border border-svika-rust bg-white p-4">
          <h2 className="text-sm font-medium text-svika-mute">ZIMRA liability (est.)</h2>
          <p className="mt-2 text-3xl font-semibold text-svika-rust">$—</p>
        </div>
      </section>

      <section className="px-6 pb-6">
        <div className="rounded-lg border border-svika-teal-100 bg-white p-6">
          <h2 className="text-base font-semibold text-svika-teal">Ghost Trip audit</h2>
          <p className="mt-2 text-sm text-svika-mute">
            Bilingual narrative generated by Gemma will render here in Phase 3.
          </p>
        </div>
      </section>
    </main>
  );
}
